### ISSUE TITLE
Eliminad matrículas de Readme

### ISSUE THREAD

**Issue by MPerezMateo** [aigora/twQ103-blibioteca-maria-moliner#1]
Sustiruid vuestras matrículas por vuestro usuario de git. Oscar me dijo que no podemos publicar información sobre los alumnos, ni siquiera matrículas, así que por favor cambiadlo. Si tenéis cualquier duda,   mandadme un mail o acudid a nuestros horarios en el laboratorio

**Comment by Juliauru** [comment]
Insistimos en que quitéis vuestros números de matrícula. Debe aparecer vuestro nombre completo y al lado el usuario de GitHub (@Juliauru )

**Comment by Juliauru** [comment]
Perfecto, ya podéis empezar a subir código.
